theme: jekyll-theme-cayman
title: 我的具身智能日报
description: 机器人 · 具身智能 · 材料前沿
baseurl: "/Horizon" # the subpath of your site, e.g. /blog
url: "https://rethinksci-gif.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
future: true # Allow future posts to be published
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - ".github"
  - "node_modules"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
